/** Working-language semantic resources. Stage 6 owns full bilingual delivery. */
export const PRESENTATION_COPY = Object.freeze({
  'app.title': 'MinePilot',
  'status.loading': 'Loading your game…',
  'status.unavailable': 'We could not safely open this game. Your saved progress has not been changed.',
  'status.committed': 'Saved.',
  'error.domain': 'That action is not available right now.',
  'error.stale': 'Your game changed elsewhere. Reload before choosing again.',
  'error.retry': 'The action was not saved. Reload and try again if your game is unchanged.',
  'error.technical': 'That action could not be completed.',
  'error.uncertain': 'The save result is uncertain. Reload before making another choice.',
  'error.recovery': 'Your saved game needs attention. No data was reset.',
  'error.unknown': 'We could not confirm the result. Reload before continuing.',
  'error.entropy': 'Secure randomness is unavailable. Your game has not changed.',
  'action.reload': 'Reload game',
  'action.retry': 'Try again',
  'action.dismiss': 'Dismiss',
  'shop.title': 'Shop',
  'shop.unavailable': 'The Shop is unavailable. Your saved game has not changed.',
  'shop.account-only': 'Finish or leave the current attempt before shopping.',
  'shop.invalid-item': 'That item is not offered.',
  'shop.insufficient-coins': 'You do not have enough coins for this item.',
  'shop.inventory-unavailable': 'This purchase cannot be completed safely.',
  'shop.unaffordable': 'Not enough coins',
  'shop.buy': 'Buy one',
  'shop.buy-again': 'Buy again',
  'shop.receipt': 'Purchase saved.',
  'shop.balance': 'Coins',
  'shop.coin': 'coins',
  'shop.owned': 'Owned',
  'shop.item.lucky': 'Lucky',
  'shop.item.detection': 'Detection',
  'shop.item.revive': 'Revive',
  'shop.item.airplane': 'Airplane',
  'settings.already-set': 'This preference is already set.',
  'tutorial.already-acknowledged': 'This tutorial step is already marked complete.',
  'error.legacy-read-only': 'This older attempt can be viewed, but cannot be changed until it is dismissed.',
  'nav.home': 'Home',
  'nav.main-label': 'Main navigation',
  'nav.levels': 'Levels',
  'nav.game': 'Game',
  'nav.shop': 'Shop',
  'nav.settings': 'Settings',
  'nav.feedback': 'Feedback',
  'nav.recovery': 'Recovery',
  'nav.continue': 'Continue',
  'nav.start': 'Start level',
  'nav.select': 'Select level',
  'nav.locked': 'Locked',
  'nav.completed': 'Completed',
  'nav.available': 'Available',
  'nav.current': 'Current attempt',
  'nav.no-attempt': 'Choose a level before entering the game.',
  'nav.confirm-replace': 'Leave the current attempt and start the selected level? This uses two separate saves and cannot be rolled back.',
  'nav.confirm': 'Confirm replacement',
  'nav.cancel': 'Cancel',
  'nav.leave-for-shop': 'Leave attempt to open Shop',
  'nav.shop-restricted': 'Shop is available only when no attempt is open. Leaving the attempt requires a separate saved action.',
  'nav.level-unavailable': 'This level is unavailable. Your saved game has not changed.',
  'nav.authority-changed': 'Your saved game changed. Reload and choose again.',
  'nav.operation-unresolved': 'Finish or cancel the current action first.',
  'nav.two-step-gap': 'The old attempt was saved as closed. Reload to check the current save; do not assume the new level started or the old attempt was restored.',
  'settings.title': 'Settings',
  'settings.music': 'Music enabled',
  'settings.effects': 'Sound effects enabled',
  'settings.saved': 'Preferences saved.',
  'feedback.title': 'Feedback',
  'feedback.open-mail': 'Send feedback by email',
  'feedback.note': 'Your email app opens only when you choose this action. No game data is uploaded automatically.',
  'recovery.title': 'Saved game unavailable',
  'recovery.note': 'Reload to try reading your save again, or contact us. Nothing has been reset or overwritten.',
  'game.region-label': 'Game presentation',
  'game.ready': 'Choose a cell to move or flag.',
  'game.board-label': 'Game board',
  'game.row': 'Row',
  'game.column': 'Column',
  'game.cell.unknown': 'Unknown cell',
  'game.cell.flagged': 'Flagged cell',
  'game.cell.explored': 'Explored cell',
  'game.cell.obstacle': 'Obstacle',
  'game.cell.revealed-mine': 'Revealed mine',
  'game.phase.active': 'Explore the board.',
  'game.phase.pending-mine-encounter': 'Mine encounter pending.',
  'game.phase.failed': 'This attempt failed.',
  'game.phase.won': 'This attempt is won.',
  'game.current-number': 'Nearby mines:',
  'game.zero-feedback': 'No nearby mines here.',
  'game.flag-target': 'Flag selected cell',
  'game.no-target': 'Select a cell to flag.',
  'game.selected': 'Selected row, column:',
  'game.mode.move': 'Touch: Move',
  'game.mode.flag': 'Touch: Flag',
  'game.position.waiting': 'Character is waiting off-board.',
  'game.position.on-board': 'Character at row, column:',
  'game.position.revealed-mine-occupancy': 'Character standing on a revealed mine at row, column:',
  'game.character-here': 'Character here',
  'home.account': 'Your account',
  'home.attempt': 'An attempt is in progress.',
  'home.no-attempt': 'Choose a level to begin.',
} as const);

export type PresentationCopyKey = keyof typeof PRESENTATION_COPY;

export function presentationCopy(key: PresentationCopyKey): string {
  return PRESENTATION_COPY[key];
}
